CREATE TABLE ORGANIZZATORE (
    P_IVA VARCHAR(11) PRIMARY KEY,
    IBAN VARCHAR(34) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    TELEFONO VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    VIA VARCHAR(50) NOT NULL,
    CITTA VARCHAR(50) NOT NULL,
    CAP VARCHAR(5) NOT NULL
);
