CREATE TABLE ORGANIZZAZIONE_CAMPIONATO (
  P_IVA_ORGANIZZATORE VARCHAR(11),
  NOME_CAMPIONATO VARCHAR(100),
  ANNO_CAMPIONATO NUMBER,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (P_IVA_ORGANIZZATORE, NOME_CAMPIONATO, ANNO_CAMPIONATO)
);
