CREATE TABLE AUTO (
    NUMERO NUMBER PRIMARY KEY,
    MARCA VARCHAR(100),
    POTENZA_CV NUMBER,
    PESO_KG NUMBER,
    MODELLO VARCHAR(100),
    ENTE_CATEGORIA VARCHAR(100),
    NOME_CATEGORIA VARCHAR(100)
);
