CREATE TABLE NOTESTEWARD (
    CODICE_STEWARD VARCHAR(100),
    DATA_ORA DATE,
    CONTENUTO VARCHAR(4000),
    SESSIONE_ID NUMBER,
    NUMERO_AUTO NUMBER,
    PRIMARY KEY (CODICE_STEWARD, DATA_ORA)
);
