CREATE TABLE ISCRIZIONE (
    ID_PILOTA NUMBER NOT NULL,
    NUMERO_AUTO NUMBER NOT NULL,
    ID_SESSIONE NUMBER NOT NULL,
    NOME_SQUADRA VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID_PILOTA, NUMERO_AUTO, ID_SESSIONE)
);
