ALTER TABLE ORGANIZZAZIONE_CAMPIONATO
    ADD FOREIGN KEY (
        P_IVA_ORGANIZZATORE
    )
        REFERENCES ORGANIZZATORE (
            P_IVA
        );

ALTER TABLE ORGANIZZAZIONE_CAMPIONATO
    ADD FOREIGN KEY (
        NOME_CAMPIONATO,
        ANNO_CAMPIONATO
    )
        REFERENCES CAMPIONATO (
            NOME,
            ANNO
        );

ALTER TABLE SPONSOR
    ADD FOREIGN KEY (
        NOME_CAMPIONATO,
        ANNO_CAMPIONATO
    )
        REFERENCES CAMPIONATO (
            NOME,
            ANNO
        );

ALTER TABLE AUTO
    ADD FOREIGN KEY (
        NOME_CATEGORIA,
        ENTE_CATEGORIA
    )
        REFERENCES CATEGORIA (
            NOME,
            ENTE_CERTIFICAZIONE
        );

ALTER TABLE SESSIONE
    ADD FOREIGN KEY (
        NOME_CAMPIONATO,
        ANNO_CAMPIONATO
    )
        REFERENCES CAMPIONATO (
            NOME,
            ANNO
        );

ALTER TABLE PASSAGGIO
    ADD FOREIGN KEY (
        NUMERO_AUTO
    )
        REFERENCES AUTO (
            NUMERO
        );

ALTER TABLE PASSAGGIO
    ADD FOREIGN KEY (
        SESSIONE_ID
    )
        REFERENCES SESSIONE (
            ID
        );

ALTER TABLE PASSAGGIO
    ADD FOREIGN KEY (
        SETTORE_SENSORE
    )
        REFERENCES SENSORE (
            SETTORE
        );

ALTER TABLE NOTESTEWARD
    ADD FOREIGN KEY (
        SESSIONE_ID
    )
        REFERENCES SESSIONE (
            ID
        );

ALTER TABLE NOTESTEWARD
    ADD FOREIGN KEY (
        NUMERO_AUTO
    )
        REFERENCES AUTO (
            NUMERO
        );

ALTER TABLE ISCRIZIONE
    ADD FOREIGN KEY (
        ID_PILOTA
    )
        REFERENCES PILOTA (
            ID
        );

ALTER TABLE ISCRIZIONE
    ADD FOREIGN KEY (
        NUMERO_AUTO
    )
        REFERENCES AUTO (
            NUMERO
        );

ALTER TABLE ISCRIZIONE
    ADD FOREIGN KEY (
        ID_SESSIONE
    )
        REFERENCES SESSIONE (
            ID
        );

ALTER TABLE ISCRIZIONE
    ADD FOREIGN KEY (
        NOME_SQUADRA
    )
        REFERENCES SQUADRA (
            NOME
        );

CREATE UNIQUE INDEX PILOTA_SESSIONE ON ISCRIZIONE (ID_PILOTA, ID_SESSIONE);
