CREATE OR REPLACE TRIGGER SESSIONI_CONTEMPORANEE BEFORE
    INSERT ON SESSIONE FOR EACH ROW
DECLARE
    NUMERO_SESSIONI INTEGER;
BEGIN
    SELECT
        COUNT(*) INTO NUMERO_SESSIONI
    FROM
        SESSIONE
    WHERE
        ( ( DATA_ORA BETWEEN :NEW.DATA_ORA
        AND :NEW.DATA_ORA + :NEW.DURATA_MIN / (24 * 60) )
        OR ( :NEW.DATA_ORA BETWEEN DATA_ORA
        AND DATA_ORA + DURATA_MIN / (24 * 60) ) );
    IF NUMERO_SESSIONI > 0 THEN
        RAISE_APPLICATION_ERROR (-20001, 'Sessioni sovrapposte');
    END IF;
END;
