CREATE OR REPLACE TRIGGER MAX_5_SPONSOR BEFORE
  INSERT ON SPONSOR FOR EACH ROW
DECLARE
  CONTATORE_SPONSOR NUMBER;
BEGIN
  SELECT
    COUNT (*) INTO CONTATORE_SPONSOR
  FROM
    SPONSOR
  WHERE
    NOME_CAMPIONATO = :NEW.NOME_CAMPIONATO
    AND ANNO_CAMPIONATO = :NEW.ANNO_CAMPIONATO;
  IF CONTATORE_SPONSOR >= 5 THEN
    RAISE_APPLICATION_ERROR (-20000, 'Numero massimo di sponsor raggiunto');
  END IF;
END;
