CREATE OR REPLACE TRIGGER SESSIONE_DURANTE_CAMPIONATO BEFORE
  INSERT ON SESSIONE FOR EACH ROW
DECLARE
  DATA_INIZIO DATE;
  DATA_FINE   DATE;
BEGIN
  SELECT
    DATA_INIZIO,
    DATA_FINE INTO DATA_INIZIO,
    DATA_FINE
  FROM
    CAMPIONATO
  WHERE
    NOME = :NEW.NOME_CAMPIONATO
    AND ANNO = :NEW.ANNO_CAMPIONATO;
  IF :NEW.DATA_ORA < DATA_INIZIO OR :NEW.DATA_ORA > DATA_FINE THEN
    RAISE_APPLICATION_ERROR (-20000, 'La sessione non è durante il campionato');
  END IF;
END;
