CREATE OR REPLACE TRIGGER PILOTA_QUALIFICHE_GARA BEFORE
  INSERT ON ISCRIZIONE FOR EACH ROW
DECLARE
  V_NUMERO_AUTO     NUMBER;
  V_NOME_SQUADRA    VARCHAR2(100);
  V_TIPO_SESSIONE   VARCHAR2(20);
  V_GARA            ISCRIZIONE%ROWTYPE := NULL;
  V_QUALIFICA       ISCRIZIONE%ROWTYPE := NULL;
  V_NOME_CAMPIONATO SESSIONE.NOME_CAMPIONATO%TYPE;
  V_ANNO_CAMPIONATO SESSIONE.ANNO_CAMPIONATO%TYPE;
BEGIN
  SELECT
    TIPO,
    NOME_CAMPIONATO,
    ANNO_CAMPIONATO INTO V_TIPO_SESSIONE,
    V_NOME_CAMPIONATO,
    V_ANNO_CAMPIONATO
  FROM
    SESSIONE
  WHERE
    ID = :NEW.ID_SESSIONE;
 
  -- per una qualifica, controlla che auto e squadra siano le stesse della gara
  IF V_TIPO_SESSIONE = 'qualifica' THEN
 
    -- trova la corrispondente gara
    BEGIN
      SELECT
        ISCRIZIONE.* INTO V_GARA
      FROM
        ISCRIZIONE
        JOIN SESSIONE
        ON ISCRIZIONE.ID_SESSIONE = SESSIONE.ID
      WHERE
        SESSIONE.NOME_CAMPIONATO = V_NOME_CAMPIONATO
        AND ISCRIZIONE.ID_PILOTA = :NEW.ID_PILOTA
        AND SESSIONE.ANNO_CAMPIONATO = V_ANNO_CAMPIONATO
        AND SESSIONE.TIPO = 'gara';
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        RETURN;
    END;

    IF :NEW.NUMERO_AUTO <> V_GARA.NUMERO_AUTO THEN
      RAISE_APPLICATION_ERROR(-20000, 'L''auto non è la stessa della gara');
    END IF;

    IF :NEW.NOME_SQUADRA <> V_GARA.NOME_SQUADRA THEN
      RAISE_APPLICATION_ERROR(-20000, 'La squadra non è la stessa della gara');
    END IF;
  END IF;
 

  -- per una gara, controlla che auto e squadra siano le stesse della qualifica
  IF V_TIPO_SESSIONE = 'gara' THEN
    BEGIN
      SELECT
        ISCRIZIONE.* INTO V_QUALIFICA
      FROM
        ISCRIZIONE
        JOIN SESSIONE
        ON ISCRIZIONE.ID_SESSIONE = SESSIONE.ID
      WHERE
        SESSIONE.NOME_CAMPIONATO = V_NOME_CAMPIONATO
        AND ISCRIZIONE.ID_PILOTA = :NEW.ID_PILOTA
        AND SESSIONE.ANNO_CAMPIONATO = V_ANNO_CAMPIONATO
        AND SESSIONE.TIPO = 'qualifica';
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        RETURN;
    END;

    IF :NEW.NUMERO_AUTO <> V_QUALIFICA.NUMERO_AUTO THEN
      RAISE_APPLICATION_ERROR(-20000, 'L''auto non è la stessa della qualifica');
    END IF;

    IF :NEW.NOME_SQUADRA <> V_QUALIFICA.NOME_SQUADRA THEN
      RAISE_APPLICATION_ERROR(-20000, 'La squadra non è la stessa della qualifica');
    END IF;
  END IF;
END;
