INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (101, 'Audi', 'R8 LMS', 590, 1250, 'FIA', 'GT3');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (102, 'Mercedes-AMG', 'GT3', 585, 1240, 'FIA', 'GT3');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (103, 'Ferrari', '488 GT3', 600, 1230, 'FIA', 'GT3');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (104, 'Lamborghini', 'Huracan GT3', 600, 1250, 'FIA', 'GT3');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (105, 'Porsche', '911 GT3 R', 550, 1200, 'FIA', 'GT3');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (106, 'Audi', 'R8 LMS', 590, 1250, 'FIA', 'GT3');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (107, 'Mercedes-AMG', 'GT3', 585, 1240, 'FIA', 'GT3');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (108, 'Ferrari', '488 GT3', 600, 1230, 'FIA', 'GT3');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (109, 'Lamborghini', 'Huracan GT3', 600, 1250, 'FIA', 'GT3');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (110, 'Porsche', '911 GT3 R', 550, 1200, 'FIA', 'GT3');

INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (200, 'Acura', 'NSX GT3', 500, 1500, 'IMSA', 'GT3');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (201, 'BMW', 'M6 GT3', 500, 1500, 'IMSA', 'GT3');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (202, 'Lexus', 'RC F GT3', 500, 1500, 'IMSA', 'GT3');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (203, 'McLaren', '720S GT3', 500, 1500, 'IMSA', 'GT3');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (204, 'Aston Martin', 'Vantage GT3', 500, 1500, 'IMSA', 'GT3');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (206, 'Acura', 'NSX GT3', 500, 1500, 'IMSA', 'GT3');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (207, 'BMW', 'M6 GT3', 500, 1500, 'IMSA', 'GT3');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (208, 'Lexus', 'RC F GT3', 500, 1500, 'IMSA', 'GT3');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (209, 'McLaren', '720S GT3', 500, 1500, 'IMSA', 'GT3');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (210, 'Aston Martin', 'Vantage GT3', 500, 1500, 'IMSA', 'GT3');

INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (300, 'Ferrari', 'F1-75', 1000, 743, 'FIA', 'Formula 1');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (301, 'Mercedes', 'W13', 1000, 748, 'FIA', 'Formula 1');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (302, 'Red Bull', 'RB18', 1000, 745, 'FIA', 'Formula 1');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (303, 'McLaren', 'MCL36', 1000, 750, 'FIA', 'Formula 1');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (304, 'Alpine', 'A522', 1000, 748, 'FIA', 'Formula 1');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (306, 'Ferrari', 'F1-75', 1000, 743, 'FIA', 'Formula 1');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (307, 'Mercedes', 'W13', 1000, 748, 'FIA', 'Formula 1');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (308, 'Red Bull', 'RB18', 1000, 745, 'FIA', 'Formula 1');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (309, 'McLaren', 'MCL36', 1000, 750, 'FIA', 'Formula 1');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (310, 'Alpine', 'A522', 1000, 748, 'FIA', 'Formula 1');

INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (400, 'Toyota', 'GR010 Hybrid', 500, 1500, 'FIA', 'LMH');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (401, 'Peugeot', '9X8', 500, 1500, 'FIA', 'LMH');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (402, 'Glickenhaus', '007 LMH', 500, 1500, 'FIA', 'LMH');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (403, 'Alpine', 'A480', 500, 1500, 'FIA', 'LMH');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (404, 'ByKolles', 'PMC Project LMH', 500, 1500, 'FIA', 'LMH');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (406, 'Toyota', 'GR010 Hybrid', 500, 1500, 'FIA', 'LMH');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (407, 'Peugeot', '9X8', 500, 1500, 'FIA', 'LMH');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (408, 'Glickenhaus', '007 LMH', 500, 1500, 'FIA', 'LMH');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (409, 'Alpine', 'A480', 500, 1500, 'FIA', 'LMH');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (410, 'ByKolles', 'PMC Project LMH', 500, 1500, 'FIA', 'LMH');

INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (500, 'Dallara', 'F2 2024', 620, 720, 'FIA', 'Formula 2');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (501, 'Dallara', 'F2 2024', 620, 720, 'FIA', 'Formula 2');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (502, 'Dallara', 'F2 2024', 620, 720, 'FIA', 'Formula 2');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (503, 'Dallara', 'F2 2024', 620, 720, 'FIA', 'Formula 2');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (504, 'Dallara', 'F2 2024', 620, 720, 'FIA', 'Formula 2');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (506, 'Dallara', 'F2 2024', 620, 720, 'FIA', 'Formula 2');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (507, 'Dallara', 'F2 2024', 620, 720, 'FIA', 'Formula 2');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (508, 'Dallara', 'F2 2024', 620, 720, 'FIA', 'Formula 2');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (509, 'Dallara', 'F2 2024', 620, 720, 'FIA', 'Formula 2');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (510, 'Dallara', 'F2 2024', 620, 720, 'FIA', 'Formula 2');

INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (600, 'Dallara', 'F3 2024', 380, 695, 'FIA', 'Formula 3');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (601, 'Dallara', 'F3 2024', 380, 695, 'FIA', 'Formula 3');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (602, 'Dallara', 'F3 2024', 380, 695, 'FIA', 'Formula 3');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (603, 'Dallara', 'F3 2024', 380, 695, 'FIA', 'Formula 3');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (604, 'Dallara', 'F3 2024', 380, 695, 'FIA', 'Formula 3');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (606, 'Dallara', 'F3 2024', 380, 695, 'FIA', 'Formula 3');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (607, 'Dallara', 'F3 2024', 380, 695, 'FIA', 'Formula 3');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (608, 'Dallara', 'F3 2024', 380, 695, 'FIA', 'Formula 3');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (609, 'Dallara', 'F3 2024', 380, 695, 'FIA', 'Formula 3');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (610, 'Dallara', 'F3 2024', 380, 695, 'FIA', 'Formula 3');

INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (700, 'Tatuus', 'F4-T014', 160, 570, 'FIA', 'Formula 4');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (701, 'Mygale', 'F4', 160, 570, 'FIA', 'Formula 4');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (702, 'Dome', 'F110', 160, 570, 'FIA', 'Formula 4');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (703, 'Onroak', 'Ligier JS F4', 160, 570, 'FIA', 'Formula 4');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (704, 'Crawford', 'F4-16', 160, 570, 'FIA', 'Formula 4');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (705, 'Tatuus', 'F4-T014', 160, 570, 'FIA', 'Formula 4');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (706, 'Mygale', 'F4', 160, 570, 'FIA', 'Formula 4');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (707, 'Dome', 'F110', 160, 570, 'FIA', 'Formula 4');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (708, 'Onroak', 'Ligier JS F4', 160, 570, 'FIA', 'Formula 4');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (709, 'Crawford', 'F4-16', 160, 570, 'FIA', 'Formula 4');

INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (800, 'Spark', 'SRT_01E', 250, 880, 'FIA', 'Formula E');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (801, 'Spark', 'SRT05e', 335, 900, 'FIA', 'Formula E');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (802, 'Spark', 'Gen2', 250, 900, 'FIA', 'Formula E');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (803, 'Spark', 'Gen3', 350, 840, 'FIA', 'Formula E');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (804, 'Spark', 'Gen3 Evo', 350, 840, 'FIA', 'Formula E');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (805, 'Spark', 'SRT_01E', 250, 880, 'FIA', 'Formula E');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (806, 'Spark', 'SRT05e', 335, 900, 'FIA', 'Formula E');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (807, 'Spark', 'Gen2', 250, 900, 'FIA', 'Formula E');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (808, 'Spark', 'Gen3', 350, 840, 'FIA', 'Formula E');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (809, 'Spark', 'Gen3 Evo', 350, 840, 'FIA', 'Formula E');

INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (900, 'Acura', 'ARX-06', 600, 900, 'IMSA', 'LMDh');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (901, 'BMW', 'M Hybrid V8', 600, 900, 'IMSA', 'LMDh');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (902, 'Cadillac', 'V-LMDh', 600, 900, 'IMSA', 'LMDh');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (903, 'Porsche', '963', 600, 900, 'IMSA', 'LMDh');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (904, 'Lamborghini', 'SC63', 600, 900, 'IMSA', 'LMDh');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (905, 'Acura', 'ARX-06', 600, 900, 'IMSA', 'LMDh');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (906, 'BMW', 'M Hybrid V8', 600, 900, 'IMSA', 'LMDh');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (907, 'Cadillac', 'V-LMDh', 600, 900, 'IMSA', 'LMDh');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (908, 'Porsche', '963', 600, 900, 'IMSA', 'LMDh');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (909, 'Lamborghini', 'SC63', 600, 900, 'IMSA', 'LMDh');

INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1000, 'Oreca', '07', 600, 930, 'IMSA', 'LMP2');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1001, 'Ligier', 'JS P217', 600, 930, 'IMSA', 'LMP2');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1002, 'Dallara', 'P217', 600, 930, 'IMSA', 'LMP2');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1003, 'Riley', 'MK. 30', 600, 930, 'IMSA', 'LMP2');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1004, 'Multimatic', 'MZ-2.0', 600, 930, 'IMSA', 'LMP2');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1005, 'Oreca', '07', 600, 930, 'IMSA', 'LMP2');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1006, 'Ligier', 'JS P217', 600, 930, 'IMSA', 'LMP2');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1007, 'Dallara', 'P217', 600, 930, 'IMSA', 'LMP2');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1008, 'Riley', 'MK. 30', 600, 930, 'IMSA', 'LMP2');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1009, 'Multimatic', 'MZ-2.0', 600, 930, 'IMSA', 'LMP2');

INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1100, 'Chevrolet', 'Camaro ZL1', 750, 1500, 'NASCAR', 'Cup Series');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1101, 'Ford', 'Mustang', 750, 1500, 'NASCAR', 'Cup Series');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1102, 'Toyota', 'Camry', 750, 1500, 'NASCAR', 'Cup Series');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1103, 'Chevrolet', 'Camaro SS', 750, 1500, 'NASCAR', 'Cup Series');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1104, 'Dodge', 'Challenger', 750, 1500, 'NASCAR', 'Cup Series');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1105, 'Chevrolet', 'Camaro ZL1', 750, 1500, 'NASCAR', 'Cup Series');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1106, 'Ford', 'Mustang', 750, 1500, 'NASCAR', 'Cup Series');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1107, 'Toyota', 'Camry', 750, 1500, 'NASCAR', 'Cup Series');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1108, 'Chevrolet', 'Camaro SS', 750, 1500, 'NASCAR', 'Cup Series');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1109, 'Dodge', 'Challenger', 750, 1500, 'NASCAR', 'Cup Series');

INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1200, 'Ford', 'Mustang GT', 635, 1395, 'Supercars', 'V8 Supercars');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1201, 'Holden', 'Commodore ZB', 635, 1395, 'Supercars', 'V8 Supercars');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1202, 'Nissan', 'Altima', 635, 1395, 'Supercars', 'V8 Supercars');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1203, 'Ford', 'Falcon FG X', 635, 1395, 'Supercars', 'V8 Supercars');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1204, 'Volvo', 'S60', 635, 1395, 'Supercars', 'V8 Supercars');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1205, 'Ford', 'Mustang GT', 635, 1395, 'Supercars', 'V8 Supercars');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1206, 'Holden', 'Commodore ZB', 635, 1395, 'Supercars', 'V8 Supercars');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1207, 'Nissan', 'Altima', 635, 1395, 'Supercars', 'V8 Supercars');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1208, 'Ford', 'Falcon FG X', 635, 1395, 'Supercars', 'V8 Supercars');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1209, 'Volvo', 'S60', 635, 1395, 'Supercars', 'V8 Supercars');

INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1300, 'Porsche', '718 Cayman GT4 RS Clubsport', 420, 1420, 'SRO', 'GT4');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1301, 'BMW', 'M4 GT4', 430, 1450, 'SRO', 'GT4');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1302, 'Aston Martin', 'Vantage GT4', 430, 1420, 'SRO', 'GT4');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1303, 'Mercedes', 'AMG GT4', 430, 1440, 'SRO', 'GT4');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1304, 'McLaren', '570S GT4', 420, 1435, 'SRO', 'GT4');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1305, 'Porsche', '718 Cayman GT4 RS Clubsport', 420, 1420, 'SRO', 'GT4');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1306, 'BMW', 'M4 GT4', 430, 1450, 'SRO', 'GT4');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1307, 'Aston Martin', 'Vantage GT4', 430, 1420, 'SRO', 'GT4');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1308, 'Mercedes', 'AMG GT4', 430, 1440, 'SRO', 'GT4');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1309, 'McLaren', '570S GT4', 420, 1435, 'SRO', 'GT4');

INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1400, 'Oreca', '07', 600, 930, 'FIA', 'LMP2');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1401, 'Ligier', 'JS P217', 600, 930, 'FIA', 'LMP2');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1402, 'Dallara', 'P217', 600, 930, 'FIA', 'LMP2');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1403, 'Riley', 'MK. 30', 600, 930, 'FIA', 'LMP2');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1404, 'Multimatic', 'MZ-2.0', 600, 930, 'FIA', 'LMP2');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1405, 'Oreca', '07', 600, 930, 'FIA', 'LMP2');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1406, 'Ligier', 'JS P217', 600, 930, 'FIA', 'LMP2');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1407, 'Dallara', 'P217', 600, 930, 'FIA', 'LMP2');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1408, 'Riley', 'MK. 30', 600, 930, 'FIA', 'LMP2');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1409, 'Multimatic', 'MZ-2.0', 600, 930, 'FIA', 'LMP2');

INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1500, 'Nissan', 'Skyline GTR', 900, 1150, 'Formula Drift', 'Pro');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1501, 'Toyota', 'Supra', 900, 1150, 'Formula Drift', 'Pro');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1502, 'Mazda', 'RX-7', 900, 1150, 'Formula Drift', 'Pro');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1503, 'Ford', 'Mustang RTR', 900, 1150, 'Formula Drift', 'Pro');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1504, 'Chevrolet', 'Camaro', 900, 1150, 'Formula Drift', 'Pro');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1505, 'Nissan', 'Skyline GTR', 900, 1150, 'Formula Drift', 'Pro');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1506, 'Toyota', 'Supra', 900, 1150, 'Formula Drift', 'Pro');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1507, 'Mazda', 'RX-7', 900, 1150, 'Formula Drift', 'Pro');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1508, 'Ford', 'Mustang RTR', 900, 1150, 'Formula Drift', 'Pro');
INSERT INTO Auto (numero, marca, modello, potenza_cv, peso_kg, ente_categoria, nome_categoria) VALUES (1509, 'Chevrolet', 'Camaro', 900, 1150, 'Formula Drift', 'Pro');
