CREATE OR REPLACE PROCEDURE ISCRIVI_AUTO(
    I_NOME_CAMPIONATO CAMPIONATO.NOME%TYPE,
    I_ANNO_CAMPIONATO CAMPIONATO.ANNO%TYPE,
    NUMERO_AUTO AUTO.NUMERO%TYPE,
    NOME_PILOTA PILOTA.NOME%TYPE,
    COGNOME_PILOTA PILOTA.COGNOME%TYPE,
    NOME_SQUADRA SQUADRA.NOME%TYPE
) IS
    PRAGMA AUTONOMOUS_TRANSACTION;
    V_CONTA_CAMPIONATO NUMBER;
    V_CONTA_AUTO       NUMBER;
    V_CONTA_PILOTA     NUMBER;
    V_CONTA_SQUADRA    NUMBER;
    V_CONTA_SESSIONE   NUMBER;
    V_ID_PILOTA        PILOTA.ID%TYPE;
BEGIN
    SELECT
        COUNT(*) INTO V_CONTA_CAMPIONATO
    FROM
        CAMPIONATO
    WHERE
        CAMPIONATO.NOME = I_NOME_CAMPIONATO
        AND CAMPIONATO.ANNO = I_ANNO_CAMPIONATO;
    IF V_CONTA_CAMPIONATO = 0 THEN
        RAISE_APPLICATION_ERROR(-20000, 'Campionato non trovato');
    END IF;

    SELECT
        COUNT(*) INTO V_CONTA_AUTO
    FROM
        AUTO
    WHERE
        AUTO.NUMERO = NUMERO_AUTO;
    IF V_CONTA_AUTO = 0 THEN
        RAISE_APPLICATION_ERROR(-20000, 'Auto non trovata');
    END IF;

    SELECT
        COUNT(*) INTO V_CONTA_PILOTA
    FROM
        PILOTA
    WHERE
        PILOTA.NOME = NOME_PILOTA
        AND PILOTA.COGNOME = COGNOME_PILOTA;
    IF V_CONTA_PILOTA = 0 THEN
        RAISE_APPLICATION_ERROR(-20000, 'Pilota non trovato');
    END IF;

    SELECT
        COUNT(*) INTO V_CONTA_SQUADRA
    FROM
        SQUADRA
    WHERE
        SQUADRA.NOME = NOME_SQUADRA;
    IF V_CONTA_SQUADRA = 0 THEN
        RAISE_APPLICATION_ERROR(-20000, 'Squadra non trovata');
    END IF;

    SELECT
        COUNT(*) INTO V_CONTA_SESSIONE
    FROM
        SESSIONE
    WHERE
        SESSIONE.NOME_CAMPIONATO = I_NOME_CAMPIONATO
        AND SESSIONE.ANNO_CAMPIONATO = I_ANNO_CAMPIONATO;
    IF V_CONTA_SESSIONE = 0 THEN
        RAISE_APPLICATION_ERROR(-20000, 'Nessuna sessione trovata per il campionato');
    END IF;

    SELECT
        PILOTA.ID INTO V_ID_PILOTA
    FROM
        PILOTA
    WHERE
        PILOTA.NOME = NOME_PILOTA
        AND PILOTA.COGNOME = COGNOME_PILOTA;
    INSERT INTO ISCRIZIONE (
        ID_PILOTA,
        NUMERO_AUTO,
        ID_SESSIONE,
        NOME_SQUADRA
    )
        SELECT
            V_ID_PILOTA,
            NUMERO_AUTO,
            SESSIONE.ID,
            NOME_SQUADRA
        FROM
            SESSIONE
            JOIN CAMPIONATO
            ON SESSIONE.ANNO_CAMPIONATO = CAMPIONATO.ANNO
            AND SESSIONE.NOME_CAMPIONATO = CAMPIONATO.NOME
        WHERE
            CAMPIONATO.NOME = I_NOME_CAMPIONATO
            AND CAMPIONATO.ANNO = I_ANNO_CAMPIONATO;
    COMMIT;
END ISCRIVI_AUTO;
