CREATE OR REPLACE PROCEDURE CREA_CAMPIONATO(
    I_NOME_CAMPIONATO CAMPIONATO.NOME%TYPE,
    I_ANNO_CAMPIONATO CAMPIONATO.ANNO%TYPE,
    I_P_IVA_ORGANIZZATORE ORGANIZZATORE.P_IVA%TYPE,
    I_DATA_INIZIO CAMPIONATO.DATA_INIZIO%TYPE,
    I_DATA_FINE CAMPIONATO.DATA_FINE%TYPE,
    I_NOME_SPONSOR SPONSOR.NOME_AZIENDA%TYPE,
    I_IMPORTO_SPONSOR SPONSOR.IMPORTO%TYPE,
    I_DATA_INIZIO_SPONSOR SPONSOR.DATA_INIZIO%TYPE,
    I_DATA_FINE_SPONSOR SPONSOR.DATA_FINE%TYPE
) IS
    V_CONTA_CAMPIONATO    NUMBER;
    V_CONTA_ORGANIZZATORE NUMBER;
BEGIN
    IF I_IMPORTO_SPONSOR <= 0 THEN
        RAISE_APPLICATION_ERROR(-20000, 'Importo sponsor non valido');
    END IF;

    IF I_DATA_INIZIO_SPONSOR > I_DATA_FINE_SPONSOR THEN
        RAISE_APPLICATION_ERROR(-20000, 'Data inizio sponsor successiva a data fine sponsor');
    END IF;

    IF I_DATA_INIZIO > I_DATA_FINE THEN
        RAISE_APPLICATION_ERROR(-20000, 'Data inizio campionato successiva a data fine campionato');
    END IF;

    SELECT
        COUNT(*) INTO V_CONTA_CAMPIONATO
    FROM
        CAMPIONATO
    WHERE
        CAMPIONATO.NOME = I_NOME_CAMPIONATO
        AND CAMPIONATO.ANNO = I_ANNO_CAMPIONATO;
    IF V_CONTA_CAMPIONATO > 0 THEN
        RAISE_APPLICATION_ERROR(-20000, 'Campionato già esistente');
    END IF;

    SELECT
        COUNT(*) INTO V_CONTA_ORGANIZZATORE
    FROM
        ORGANIZZATORE
    WHERE
        ORGANIZZATORE.P_IVA = I_P_IVA_ORGANIZZATORE;
    IF V_CONTA_ORGANIZZATORE = 0 THEN
        RAISE_APPLICATION_ERROR(-20000, 'Organizzatore non trovato');
    END IF;

    INSERT INTO CAMPIONATO VALUES (
        I_NOME_CAMPIONATO,
        I_ANNO_CAMPIONATO,
        I_DATA_INIZIO,
        I_DATA_FINE
    );
    INSERT INTO SPONSOR VALUES (
        I_NOME_SPONSOR,
        I_DATA_INIZIO_SPONSOR,
        I_DATA_FINE_SPONSOR,
        I_IMPORTO_SPONSOR,
        I_NOME_CAMPIONATO,
        I_ANNO_CAMPIONATO
    );
    INSERT INTO ORGANIZZAZIONE_CAMPIONATO VALUES(
        I_P_IVA_ORGANIZZATORE,
        I_NOME_CAMPIONATO,
        I_ANNO_CAMPIONATO,
        SYSDATE
    );
END;
