CREATE VIEW VISTA_SPONSOR_ATTIVI AS
    SELECT
        S.NOME_AZIENDA,
        S.IMPORTO,
        S.DATA_INIZIO,
        S.DATA_FINE,
        C.NOME         AS NOME_CAMPIONATO,
        C.ANNO         AS ANNO_CAMPIONATO
    FROM
        SPONSOR    S
        JOIN CAMPIONATO C
        ON S.NOME_CAMPIONATO = C.NOME
        AND S.ANNO_CAMPIONATO = C.ANNO
    WHERE
        S.DATA_FINE >= SYSDATE;
